version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Installing dependencies
      - pip install -r scraper/requirements.txt
  build:
    commands:
      - echo Running tests
      - pytest --maxfail=1 --disable-warnings -q
artifacts:
  files:
    - appspec.yml
    - scraper/**/*
    - scripts/**/*
